# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/HZWZ-L/kernel_build_actionOnePlus6-4.19
          kernel-dir: msm-4.19
          kernel-branch: Main
          config: vendor/sdm845-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          ksu: true
          ksu-version: main
          android-version: 15
          aosp-clang-version: 
          disable-lto: true
          anykernel3: true
